title: "Emanuele Locatelli's Personal Website"
description: "Welcome to my Jekyll-powered site!"
author: "Emanuele Locatelli"

# Theme (GitHub Pagesâ€“compatible)
remote_theme: pages-themes/minimal@v0.2.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
